# Generated by Django 4.0.4 on 2022-05-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='type',
        ),
    ]
