# Generated by Django 4.0.4 on 2022-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0002_remove_movies_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.FloatField(),
        ),
    ]
