# Generated by Django 4.0.4 on 2022-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0002_alter_watchlist_rating_alter_watchlist_watched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
