# Generated by Django 4.0.4 on 2022-05-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0003_alter_watchlist_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='type',
        ),
    ]
